from ros:humble-perception
# FROM ubuntu:jammy-20230301

# # ROS install instructions from https://linuxopsys.com/topics/install-ros-2-humble-on-ubuntu
# RUN apt update && apt install locales && locale-gen en_US en_US.UTF-8 && export LANG=en_US.UTF-8
# RUN apt-get install -y software-properties-common curl gnupg lsb-release
# RUN add-apt-repository universe 
# RUN apt update 
# RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg 
# RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu jammy main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null
# RUN apt-get update && apt-get install -y ros-humble-desktop
