#!/bin/sh
# docker run -it --rm -w /root/car_ws --name car  --network host --device /dev/car-controller -e SHELL=/bin/bash --device /dev/car-lidar -v ~/car_ws:/root/car_ws brianerickson/ros2 /bin/bash -c "screen -q; exit"
ws=$(pwd)
uid=$(id -u)
gid=$(id -g)

docker run -it --rm -w $ws \
  --name car  \
  --network host \
  --env="DISPLAY" \
  --env="QT_X11_NO_MITSHM=1" \
  --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" \
  --device /dev/car-controller \
  --device  /dev/ttyACM0 \
  --privileged -e SHELL=/bin/bash \
  --device /dev/rplidar \
  --volume $HOME:$HOME \
  brianerickson/ros2 /bin/bash -c "screen -q; exit"

# ros2 run micro_ros_agent micro_ros_agent serial --dev /dev/ttyACM0

#  --volume /etc/passwd:/etc/passwd:ro \
#  --volume /etc/group:/etc/group:ro \
#  --user $uid:$gid \


#  --volume $HOME/.ros:/$HOME/.ros \
#  --volume $ws:$ws \
