car:
  ros__parameters:
    robot_id: bluebot
    camera_pitch_degrees: 3.5
    camera_yaw_degrees: -2.0
    camera_roll_degrees: 1.0
    camera_x: 0.27
    camera_z: 0.135
    compass_correction_degrees: 160.0
    compass_error_degrees: 5.0
    compass_error_factor: 1000.0 # makes navigation less sensitive to compass errors
    lidar_x: 0.140
    lidar_z: 0.175
    mag_x_min: -650.0
    mag_x_max: 900.0
    mag_y_min: -302.0
    mag_y_max: 1180.0

    curvature_to_str_lookup: [
      -85.1, 1844.0,
      -71.9, 1744.0,
      -58.2, 1709.0,
      -44.1, 1674.0,
      -29.6, 1593.0,
      -14.8, 1514.0,
      0.0, 1436.0,
      14.8, 1376.0,
      29.6, 1254.0,
      44.0, 1221.0,
      58.2, 1175.0,
      71.9, 1090.0,
      85.1, 986.0 
    ]

gps_fixer:
  ros__parameters:
    error_scalar: 100.0 # makes navigation less sensitive to GPS errors