car:
  ros__parameters:
    robot_id: "bluebot"

    front_left_meters_per_tick: 0.003087
    front_right_meters_per_tick: 0.003112
    motor_meters_per_tick: 0.0033876

    camera_pitch_degrees: 3.5
    camera_yaw_degrees: -2.0
    camera_roll_degrees: 1.0
    camera_x: 0.27
    camera_z: 0.155
    compass_correction_degrees: 179.0
    compass_error_degrees: 5.0
    compass_error_factor: 5.0 # makes navigation less sensitive to compass errors
    lidar_x: 0.140
    lidar_z: 0.195

    # eldo
    # mag_x_min: -500.0 # -650.0
    # mag_x_max: 950.0 # 900.0
    # mag_y_min: -302.0
    # mag_y_max: 1180.0

    # san jose
    mag_x_max: 893.0
    mag_x_min: -408.0
    mag_y_max: 1087.0
    mag_y_min: -167.0


    curvature_to_str_lookup: [
      -85.1, 1844.0,
      -71.9, 1744.0,
      -58.2, 1709.0,
      -44.1, 1674.0,
      -29.6, 1593.0,
      -14.8, 1514.0,
      0.0, 1445.0,
      14.8, 1376.0,
      29.6, 1254.0,
      44.0, 1221.0,
      58.2, 1175.0,
      71.9, 1090.0,
      85.1, 986.0 
    ]

gps_fixer:
  ros__parameters:
    min_std: 2.0      # minimum GPS standard deviation to report
    error_factor: 1.0 # multiplier for reported errors, higher numbers make navigation less sensitive to GPS errors

cone_follower_node:
  ros__parameters:
    goal_distance: 0.15
    accel: 0.3
    max_velocity: 2.0
    min_velocity: 0.1

